openapi: 3.0.0
servers:
  - url: localhost:8080
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
paths:
  /iniciar:
    post:
      summary: Iniciar
      requestBody:
        content: {}
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:39:42 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                numeroDaRodada: 1
                cartas:
                  - imdbId: tt0110857
                    titulo: 'Academia de Polícia VII: Missão em Moscovo'
                    ano: 0
                    imagem: >-
                      https://m.media-amazon.com/images/M/MV5BNmM5MzA3YTMtZDZkNy00YzNlLWFkZTUtZDJhYTNkMzk1ODNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY67_CR0,0,45,67_AL_.jpg
                    hashImdbId: 110857
                  - imdbId: tt1832382
                    titulo: Uma Separação
                    ano: 0
                    imagem: >-
                      https://m.media-amazon.com/images/M/MV5BN2JmMjViMjMtZTM5Mi00ZGZkLTk5YzctZDg5MjFjZDE4NjNkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY67_CR0,0,45,67_AL_.jpg
                    hashImdbId: 1832382
                imdbEscolhido: null
  /proxima/tt10886166:
    post:
      tags:
        - default
      summary: Próxima rodada
      requestBody:
        content: {}
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:39:58 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                numeroDaRodada: 2
                cartas:
                  - imdbId: tt1464335
                    titulo: Uncharted
                    ano: 0
                    imagem: >-
                      https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UY67_CR0,0,45,67_AL_.jpg
                    hashImdbId: 1464335
                  - imdbId: tt1291584
                    titulo: Warrior - Combate Entre Irmãos
                    ano: 0
                    imagem: >-
                      https://m.media-amazon.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_UX45_CR0,0,45,67_AL_.jpg
                    hashImdbId: 1291584
                imdbEscolhido: null
        '400':
          description: Bad Request
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: text/plain;charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '34'
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:40:11 GMT
            Connection:
              schema:
                type: string
                example: close
          content:
            text/plain:
              schema:
                type: string
              example: O ImdbId informado não é válido
  /status:
    get:
      tags:
        - default
      summary: Status
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:38:08 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                id: 2
                dataInicio: '2022-08-15T18:35:55.020767'
                jogador:
                  nome: user
                  ultimoAcesso: '2022-08-15T18:35:54.985208'
                  pontuacaoRecord: null
                erros: 1
                emAndamento: true
                rodadaAtual:
                  numeroDaRodada: 2
                  cartas:
                    - imdbId: tt9419884
                      titulo: Doutor Estranho no Multiverso da Loucura
                      ano: 0
                      imagem: >-
                        https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UY67_CR0,0,45,67_AL_.jpg
                      hashImdbId: 9419884
                    - imdbId: tt0266697
                      titulo: Kill Bill - A Vingança (vol. 1)
                      ano: 0
                      imagem: >-
                        https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX45_CR0,0,45,67_AL_.jpg
                      hashImdbId: 266697
                  imdbEscolhido: null
                motivoTerminoDaPartida: null
                rodadas:
                  - numeroDaRodada: 1
                    cartas:
                      - imdbId: tt0117951
                        titulo: Trainspotting
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BMzA5Zjc3ZTMtMmU5YS00YTMwLWI4MWUtYTU0YTVmNjVmODZhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY67_CR0,0,45,67_AL_.jpg
                        hashImdbId: 117951
                      - imdbId: tt10886166
                        titulo: 365 Dias
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BMDdhYzNkOWQtYWNlNi00NDdjLWJlZDMtMjJjZDYyNjAxM2U1XkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_UY67_CR2,0,45,67_AL_.jpg
                        hashImdbId: 10886166
                    imdbEscolhido: tt10886166
                  - numeroDaRodada: 2
                    cartas:
                      - imdbId: tt9419884
                        titulo: Doutor Estranho no Multiverso da Loucura
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UY67_CR0,0,45,67_AL_.jpg
                        hashImdbId: 9419884
                      - imdbId: tt0266697
                        titulo: Kill Bill - A Vingança (vol. 1)
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX45_CR0,0,45,67_AL_.jpg
                        hashImdbId: 266697
                    imdbEscolhido: null
                score: 0
  /desistir:
    post:
      tags:
        - default
      summary: Desistir
      requestBody:
        content: {}
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:38:41 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                id: 2
                dataInicio: '2022-08-15T18:35:55.020767'
                jogador:
                  nome: user
                  ultimoAcesso: '2022-08-15T18:35:54.985208'
                  pontuacaoRecord: 0
                erros: 1
                emAndamento: false
                rodadaAtual:
                  numeroDaRodada: 2
                  cartas:
                    - imdbId: tt9419884
                      titulo: Doutor Estranho no Multiverso da Loucura
                      ano: 0
                      imagem: >-
                        https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UY67_CR0,0,45,67_AL_.jpg
                      hashImdbId: 9419884
                    - imdbId: tt0266697
                      titulo: Kill Bill - A Vingança (vol. 1)
                      ano: 0
                      imagem: >-
                        https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX45_CR0,0,45,67_AL_.jpg
                      hashImdbId: 266697
                  imdbEscolhido: null
                motivoTerminoDaPartida: Desistiu
                rodadas:
                  - numeroDaRodada: 1
                    cartas:
                      - imdbId: tt0117951
                        titulo: Trainspotting
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BMzA5Zjc3ZTMtMmU5YS00YTMwLWI4MWUtYTU0YTVmNjVmODZhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY67_CR0,0,45,67_AL_.jpg
                        hashImdbId: 117951
                      - imdbId: tt10886166
                        titulo: 365 Dias
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BMDdhYzNkOWQtYWNlNi00NDdjLWJlZDMtMjJjZDYyNjAxM2U1XkEyXkFqcGdeQXVyMTQyMTMwOTk0._V1_UY67_CR2,0,45,67_AL_.jpg
                        hashImdbId: 10886166
                    imdbEscolhido: tt10886166
                  - numeroDaRodada: 2
                    cartas:
                      - imdbId: tt9419884
                        titulo: Doutor Estranho no Multiverso da Loucura
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UY67_CR0,0,45,67_AL_.jpg
                        hashImdbId: 9419884
                      - imdbId: tt0266697
                        titulo: Kill Bill - A Vingança (vol. 1)
                        ano: 0
                        imagem: >-
                          https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX45_CR0,0,45,67_AL_.jpg
                        hashImdbId: 266697
                    imdbEscolhido: null
                score: 0
  /top10:
    get:
      tags:
        - default
      summary: Top10
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:40:37 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                - nome: user
                  ultimoAcesso: '2022-08-15T18:39:42.480232'
                  pontuacaoRecord: 0
                - nome: user1
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user2
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user3
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user4
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user5
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user6
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user7
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user8
                  ultimoAcesso: null
                  pontuacaoRecord: null
                - nome: user9
                  ultimoAcesso: null
                  pontuacaoRecord: null
  /meuRanking:
    get:
      tags:
        - default
      summary: MeuRanking
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Mon, 15 Aug 2022 17:40:41 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example: 6
info:
  contact:
    email: marcel.tanuri@gmail.com
    url: https://github.com/marceltanuri/card-game-imdb
  version: 1.0.0
  title: card-game-imdb